version: "3"
services:
    siep-admin:
      restart: always
      image: nginx:alpine
      container_name: siep-admin
      working_dir: /application
      volumes:
          - ..:/application
          - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "81:80"
      environment:
        - DB_HOST=siep-mysql
        - DB_DATABASE=siep
        - DB_USERNAME=siep
        - DB_PASSWORD=siep
        - API_GATEWAY_HOST=http://siep-api-gw
      depends_on:
        - siep-admin-node
      networks:
        - siep-lan

    siep-admin-node:
      image: node:alpine
      container_name: siep-admin-node
      volumes:
         - "..:/application"
      working_dir: "/application/webpack"
      command: sh -c "npm install && npm run build"         
      networks:
         - siep-lan

networks:
  siep-lan:
    driver: bridge
